<?php


namespace ScandiPWA\Logger;


use Magento\Framework\Logger\Monolog;
use Monolog\Handler\StreamHandler;

class Cloud extends Monolog
{
    public function addRecord($level, $message, array $context = [])
    {
        $this->setHandlers([new StreamHandler('php://stderr', static::DEBUG)]);
        
        return parent::addRecord($level, $message, $context); // TODO: Change the autogenerated stub
    }
}